### ISSUE TITLE
'crypto not defined'

### ISSUE THREAD

**Issue by gabemhouts** [nbd-wtf/nostr-tools#160]
When trying to encrypt direct messages, as per the documentation, I am receiving the 'crypto is not defined' error and cant figure out how to fix it.

```
C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\node_modules\nostr-tools\lib\nostr.cjs.js:748
  let cryptoKey = await crypto.subtle.importKey(
                  ^

ReferenceError: crypto is not defined
    at Object.encrypt (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\node_modules\nostr-tools\lib\nostr.cjs.js:748:19)
    at C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:48:56
    at step (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:33:23)
    at Object.next (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:14:53)
    at C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:4:12)
    at sendMessage (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\nostr\direct-messages.js:44:12)
    at Object.<anonymous> (C:\Users\gabem\OneDrive\Documents\GitHub\nostr-client\dist\index.js:19:35)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0
```

**Comment by fiatjaf** [comment]
Is this react-native-related?

**Comment by gabemhouts** [comment]
Not, im currently trying to build with express, but might switch to react soon. I was able to fix the issue by requiring 'crypto' in nostr.cjs.js. I dont know if this is a good fix, feels a bit like a bodge, but its working for now.

**Comment by vgenev** [comment]
I am experiencing the same issue with nodejs.
Also it needs node 18, which is my stack issue, though.

**Comment by bumi** [comment]
had a similar issue in some node environment, a workaround could be (did not spend much time on it): 
```
import * as crypto from 'node:crypto';
globalThis.crypto = crypto;
```
