### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins 

### ISSUE THREAD

**Issue by sven-hash** [nbd-wtf/nostr-tools#228]
Error when building
Versions are:
* nostr-tools: ^1.12.0
* npm: 9.6.3
* node: v19.9.0 or v20.0.3
* next: 13.4.3

```
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:28:395974
    at Hook.eval [as callAsync] (eval at create (iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
    at Object.processResource (iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:28:395899)
    at processResource (iris-nextjs/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (iris-nextjs/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
    at runLoaders (iris-nextjs/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
    at NormalModule._doBuild (iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:28:395761)
    at NormalModule.build (iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:28:397789)
    at iris-nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:28:81243

Import trace for requested module:
node:crypto
./node_modules/@noble/hashes/esm/cryptoNode.js
./node_modules/@noble/hashes/esm/utils.js
./node_modules/nostr-tools/lib/esm/nostr.mjs
./app/(messages)/messages/[address]/page.tsx
```

**Comment by sven-hash** [comment]
Update to next 13.4.5 seems to do the trick
